root = "."
tmp_dir = "tmp"

[build]
cmd = "mise run build:templ && go build -o ./tmp/main ./cmd/www-fmind-dev"
bin = "./tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "css", "templ"]
exclude_regex = ["_test.go", "_templ.go"]
stop_on_error = true
